version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    groups:
      # Group all development dependencies together
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "@typescript-eslint/*"
          - "jest*"
          - "prettier*"
          - "husky"
          - "lint-staged"
        update-types:
          - "minor"
          - "patch"
      # Group TypeScript and build tools
      build-tools:
        patterns:
          - "typescript"
          - "tsx"
          - "ts-*"
        update-types:
          - "minor"
          - "patch"
    # Only allow patch and minor updates (no major version bumps)
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable security updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "security"
      - "dependencies"
    commit-message:
      prefix: "fix"
      include: "scope"