# Configuration for the labeler action
# Add labels based on file paths

documentation:
  - changed-files:
    - any-glob-to-any-file: 
      - docs/**
      - '*.md'
      - LICENSE

tests:
  - changed-files:
    - any-glob-to-any-file:
      - tests/**
      - '**/*.test.ts'
      - '**/*.spec.ts'
      - jest.config.js

cli:
  - changed-files:
    - any-glob-to-any-file: src/cli/**

core:
  - changed-files:
    - any-glob-to-any-file: src/core/**

git:
  - changed-files:
    - any-glob-to-any-file: src/core/git/**

sessions:
  - changed-files:
    - any-glob-to-any-file: src/sessions/**

ci:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/**
      - .github/actions/**
      - Dangerfile.js

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - package.json
      - package-lock.json

config:
  - changed-files:
    - any-glob-to-any-file:
      - tsconfig.json
      - jest.config.js
      - .eslintrc.js
      - .prettierrc
      - .gitignore
      - .npmignore